---
blank_issues_enabled: false
contact_links:
  - name: General question
    url: https://github.com/philsherry/govuk-design-system-skills/discussions
    about: Ask a question or start a discussion
